/**
 * validate-llms.ts — verifies that the shipped raw llms.txt matches the
 * canonical content rendered by the human-readable llms.txt page.
 *
 * Run with: node --experimental-strip-types scripts/validate-llms.ts
 * Exits non-zero when the raw file has drifted from the shared content source.
 */

import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  LLMS_TXT_SECTIONS,
  buildBlogIndexSubsections,
  renderLlmsTxt,
  renderLlmsTxtPrerenderHtml,
  type LlmsSubsection,
} from '../src/data/llmsContent.ts';
import { BLOG_POSTS } from '../src/data/blogPosts.ts';
import { getRouteBodyHtml } from '../src/lib/routeContent.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rawFilePath = join(__dirname, '..', 'public', 'llms.txt');
const expected = renderLlmsTxt();
const actual = readFileSync(rawFilePath, 'utf-8');
const blogIndex = LLMS_TXT_SECTIONS.find(
  (section) => section.heading === 'Blog Content Index',
);

if (!blogIndex?.subsections) {
  console.error(
    'llms.txt validation FAILED: the canonical content model is missing its Blog Content Index.',
  );
  process.exit(1);
}

const expectedBlogIndex = buildBlogIndexSubsections(BLOG_POSTS);
const renderSubsections = (subsections: LlmsSubsection[]) =>
  subsections
    .map((subsection) => `### ${subsection.subheading}\n\n${subsection.content}`)
    .join('\n\n');

if (renderSubsections(blogIndex.subsections) !== renderSubsections(expectedBlogIndex)) {
  console.error(
    'llms.txt validation FAILED: Blog Content Index titles, summaries, or URLs are out of sync with the published blog catalogue.',
  );
  console.error(
    'The index is generated by buildBlogIndexSubsections() in src/data/llmsContent.ts — restore that generation instead of hand-editing entries.',
  );
  process.exit(1);
}

const indexedArticleCount = blogIndex.subsections.reduce(
  (total, subsection) => total + subsection.content.split(/\n\n+/).length,
  0,
);

if (indexedArticleCount !== BLOG_POSTS.length) {
  console.error(
    `llms.txt validation FAILED: Blog Content Index lists ${indexedArticleCount} article(s) but the catalogue publishes ${BLOG_POSTS.length}.`,
  );
  process.exit(1);
}

if (actual !== expected) {
  const expectedLines = expected.split('\n');
  const actualLines = actual.split('\n');
  const firstDifference = expectedLines.findIndex(
    (line, index) => line !== actualLines[index],
  );
  const lineNumber = firstDifference === -1
    ? Math.min(expectedLines.length, actualLines.length) + 1
    : firstDifference + 1;

  console.error(
    `llms.txt validation FAILED: public/llms.txt differs from the canonical content source at line ${lineNumber}.`,
  );
  console.error(
    'Update the canonical content in src/data/llmsContent.ts, then run `pnpm run sync:llms`.',
  );
  process.exit(1);
}

if (getRouteBodyHtml('/llms-txt') !== renderLlmsTxtPrerenderHtml()) {
  console.error(
    'llms.txt validation FAILED: the prerendered /llms-txt body is not generated from the canonical content source.',
  );
  process.exit(1);
}

console.log(
  'llms.txt validation passed: raw file and prerender source both match the canonical content model.',
);